### ISSUE TITLE
Duplicate entries in left menu

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama-platform.github.io#47] opened 2019-05-14 15:32 UTC
It seems that all the intermediate items are duplicated in the menu, which does not improve the navigation nor the length of the menu ... 

<img width="136" alt="image" src="https://user-images.githubusercontent.com/579256/57710979-1cb15100-7698-11e9-9984-6c1ae9b76f8c.png">

**Comment by RoiArthurB** [comment] 2019-05-16 07:29
Hello,

I know it, but the problem is that if I add a link on the main section, it's very difficult (and impossible on smartphone) to display the sub-menu.

So I preferred having duplicated lines rather deleting pages.

**Comment by RoiArthurB** [comment] 2019-05-16 09:02
Should be fixed in commit 56bc5987fdfea42d9777b1a3582ac51812160aa3

**Closed by RoiArthurB** 2019-05-16 09:02 UTC
Labels: bug, improve content
