### ISSUE TITLE
No results when taping "batch" in the search bar

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama-platform.github.io#51] opened 2019-05-16 07:07 UTC
I don't if it's because it's not documented or not parse but 0 results appear when typing ````batch````in the search bar.

It's the first world I was playing with I guess there is a lot of case like that, how to we proceed shoudl post an issue for each case like this?

**Comment by RoiArthurB** [comment] 2019-05-16 08:06
The search engine is in active development. It's currently lacking a lot of keywords, but they will be added as soon as possible!

**Comment by RoiArthurB** [comment] 2019-05-16 09:41
Duplicate of #36

**Closed by RoiArthurB** 2019-05-16 09:41 UTC
Labels: search_engine
